include: package:flutter_lints/flutter.yaml
linter:
  rules:
    prefer_single_quotes: false
    constant_identifier_names: false
    non_constant_identifier_names: false
    unnecessary_this: false
    avoid_renaming_method_parameters: false
    require_trailing_commas: true
    library_private_types_in_public_api: false