name: tone_player
description:
version: 0.0.1
homepage:
environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"
dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.robmllze.tone_player
        pluginClass: TonePlayerPlugin
      ios:
        pluginClass: TonePlayerPlugin
      macos:
        pluginClass: TonePlayerPlugin
