name: tone_player_example
description: Demonstrates how to use the tone_player plugin.
publish_to: 'none'
environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  tone_player:
    path: ../
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
